# Generated by Django 5.1.6 on 2025-04-05 10:01

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gotale", "0003_alter_scenario_root_step"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="history",
            options={"ordering": ["-created"]},
        ),
        migrations.RemoveField(
            model_name="game",
            name="start",
        ),
        migrations.RemoveField(
            model_name="history",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="location",
            name="name",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="name",
        ),
        migrations.RemoveField(
            model_name="step",
            name="text",
        ),
        migrations.AddField(
            model_name="game",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="location",
            name="title",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, verbose_name="title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scenario",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scenario",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="scenario",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="title",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, verbose_name="title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="step",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="step",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
    ]
