# Generated by Django 5.1.6 on 2025-04-19 10:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gotale", "0005_location_created_location_modified_alter_location_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
