# Generated by Django 5.1.6 on 2025-04-21 16:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gotale", "0006_alter_scenario_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
