# Generated by Django 5.1.6 on 2025-04-21 18:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gotale", "0007_alter_choice_id_alter_step_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="game",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
